use std::env;
use std::fs::{self, File};
use std::io::{self, Write};
use std::path::PathBuf;

fn main() -> io::Result<()> {
    println!("cargo:rerun-if-changed=test");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let tests_dir = manifest_dir.join("test");
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("tests.rs");

    let mut targets: Vec<String> = fs::read_dir(&tests_dir)?
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let path = entry.path();
            if path.extension()?.to_str()? != "rs" {
                return None;
            }
            Some(path.file_stem()?.to_string_lossy().into_owned())
        })
        .collect();

    targets.sort();

    println!("cargo:rustc-check-cfg=cfg(build_all_targets)");
    if !targets.is_empty() {
        let values = targets
            .iter()
            .map(|name| format!("\"{}\"", name))
            .collect::<Vec<_>>()
            .join(", ");
        println!("cargo:rustc-check-cfg=cfg(target_name, values({values}))");
    }

    let mut out = File::create(out_path)?;
    writeln!(out, "// @generated by build.rs -- do not edit")?;
    write!(out, "pub const TARGETS: &[&str] = &[")?;
    for (idx, target) in targets.iter().enumerate() {
        if idx > 0 {
            write!(out, ", ")?;
        }
        write!(out, "\"{}\"", target)?;
    }
    writeln!(out, "];\n")?;

    for target in &targets {
        let source_path = tests_dir.join(format!("{}.rs", target));
        writeln!(out, "#[cfg(any(build_all_targets, target_name = \"{}\"))]", target)?;
        writeln!(out, "#[path = {:?}]", source_path)?;
        writeln!(out, "pub mod {};", target)?;
        writeln!(out, "#[cfg(any(build_all_targets, target_name = \"{}\"))]", target)?;
        writeln!(out, "pub use {}::*;", target)?;
        writeln!(out)?;
    }

    Ok(())
}
