use std::env;
use std::fs::{self, File};
use std::io::{self, Write};
use std::path::{Path, PathBuf};

struct TestEntry {
    rel_path: PathBuf,
    cfg_key: String,
    module_name: String,
}

fn main() -> io::Result<()> {
    println!("cargo:rerun-if-changed=test");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let tests_dir = manifest_dir.join("test");
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("tests.rs");

    let mut targets = collect_targets(&tests_dir)?;
    targets.sort_by(|a, b| a.cfg_key.cmp(&b.cfg_key));

    println!("cargo:rustc-check-cfg=cfg(build_all_targets)");
    if !targets.is_empty() {
        let values = targets
            .iter()
            .map(|target| format!("\"{}\"", target.cfg_key))
            .collect::<Vec<_>>()
            .join(", ");
        println!("cargo:rustc-check-cfg=cfg(target_name, values({values}))");
    }

    let mut out = File::create(out_path)?;
    writeln!(out, "// @generated by build.rs -- do not edit")?;
    write!(out, "pub const TARGETS: &[&str] = &[")?;
    for (idx, target) in targets.iter().enumerate() {
        if idx > 0 {
            write!(out, ", ")?;
        }
        write!(out, "\"{}\"", target.cfg_key)?;
    }
    writeln!(out, "];\n")?;

    for target in &targets {
        let source_path = tests_dir.join(&target.rel_path);
        writeln!(out, "#[cfg(any(build_all_targets, target_name = \"{}\"))]", target.cfg_key)?;
        writeln!(out, "#[path = {:?}]", source_path)?;
        writeln!(out, "pub mod {};", target.module_name)?;
        writeln!(out, "#[cfg(any(build_all_targets, target_name = \"{}\"))]", target.cfg_key)?;
        writeln!(out, "pub use {}::*;", target.module_name)?;
        writeln!(out)?;
    }

    Ok(())
}

fn collect_targets(tests_dir: &Path) -> io::Result<Vec<TestEntry>> {
    let mut entries = Vec::new();
    walk_tests(tests_dir, tests_dir, &mut entries)?;
    Ok(entries)
}

fn walk_tests(base: &Path, dir: &Path, entries: &mut Vec<TestEntry>) -> io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            walk_tests(base, &path, entries)?;
            continue;
        }
        if path.extension().and_then(|ext| ext.to_str()) != Some("rs") {
            continue;
        }
        let rel_path = path.strip_prefix(base).unwrap().to_path_buf();
        let rel_base = rel_path.with_extension("");
        let cfg_key = rel_base.to_string_lossy().replace('\\', "/");
        let module_name = sanitize_module_name(&rel_base);
        entries.push(TestEntry {
            rel_path,
            cfg_key,
            module_name,
        });
    }
    Ok(())
}

fn sanitize_module_name(path: &Path) -> String {
    let raw = path.to_string_lossy().replace('\\', "/");
    let mut result = String::new();
    for ch in raw.chars() {
        match ch {
            '/' => result.push_str("__"),
            '-' | '.' => result.push('_'),
            c if c.is_ascii_alphanumeric() || c == '_' => result.push(c),
            _ => result.push('_'),
        }
    }
    if result.is_empty() || result.chars().next().unwrap().is_ascii_digit() {
        result.insert(0, '_');
    }
    result
}
